language: node_js
node_js:
  - '4'
  - '5'
  - '6'
sudo: false
script:
  make test
cache:
  directories:
    - node_modules
after_success: npm i coveralls && $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls
